### ISSUE TITLE
Needs support for Azure HyperV-based stemcells

### ISSUE THREAD

**Issue by joshuamckenty** [cloudfoundry-community/redis-boshrelease#41]
CI pipeline builds only for AWS KVM stemcells.

**Comment by drnic** [comment]
The use of aws stemcells is because the target bosh is on aws (previously I
had a bosh-lite but have consolidated to just one bosh for CI); yet the
resulting compiled releases will work with any bosh using ubuntu-xenial
stemcells (currently 250.latest; but soon will hump to 456.latest).

The delightfulness of bosh, and noteworthily this specific release, is that
there is no need (IMO) to test the release on a range of iaas clouds.

Sound good?
-- 
Dr Nic Williams
Stark & Wayne LLC
http://starkandwayne.com
+61 437 276 076
twitter @drnic

**Comment by joshuamckenty** [comment]
Because they’re precompiled releases with no source code, they don’t work in other targets.

**Comment by drnic** [comment]
Precompiled releases work in any iaas. cf-deployment is an example of a
bosh deployment that makes precompiled releases available - they can be
uploaded to any bosh on any CPI.

As an aside, the precompiled releases do not need to be used. A deployer of
this release can use the source-based release included in the GitHub
release or re-create it themselves via this repo.
-- 
Dr Nic Williams
Stark & Wayne LLC
http://starkandwayne.com
+61 437 276 076
twitter @drnic

**Comment by drnic** [comment]
Closing. Happy to chat more about this if more questions.

**Comment by joshuamckenty** [comment]
I'll submit a PR when I have time - didn't screenshot the error because I thought this would be simple to explain.

**Comment by drnic** [comment]
Thanks @joshuamckenty. If its failing on Azure, I'm happy to help.
